import type { Metadata } from "next";
import "../../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import DefaultLayout from "@/layout/DashBoardLayout";

export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <DefaultLayout>
      {children}
      </DefaultLayout>
      
      </body>
      </html>
  );
}
