import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import { cn } from "@/lib/utils";
import NavBar from '@/components/Navbar'
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";


const poppin = Poppins({ subsets: ["devanagari"], weight: "300"});

export const metadata: Metadata = {
  title: "Site App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
      >
        <NavBar/>
        <Toaster/>
       <main>
       {
          children
        }
       </main>
        <Footer/>
      </body>
    </html>
  );
}
